### ISSUE TITLE
Weird scope issues and internal errors

### ISSUE THREAD

**Issue by Bartvds** [shama/grunt-benchmark#11]
I get internal errors and weird issues where a ReferenceError is thrown on a enclosed 
variable:

I only get the stack if I use `--stack` with grunt, and it shows _after_ the actual error message with some other output in-between.

```
>> Error running test original: ReferenceError: original is not defined
>> current x 798,874 ops/sec ±0.75% (95 runs sampled)
Warning: Cannot read property 'hz' of undefined Use --force to continue.
TypeError: Cannot read property 'hz' of undefined
    at Suite.<anonymous> (d:\project\node_modules\grunt-benchmark\tasks\lib\benchmark.js:214:54)
    at d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:2108:38
    at forEach (d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:1527:11)
    at Suite.emit (d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:2107:7)
    at Suite.invoke.onComplete (d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:2080:12)
    at getNext (d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:1740:28)
    at execute (d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:1702:24)
    at invoke (d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:1814:18)
    at Suite.runSuite [as run] (d:\project\node_modules\grunt-benchmark\node_modules\benchmark\benchmark.js:2063:5)
    at Object.runBench (d:\project\node_modules\grunt-benchmark\tasks\lib\benchmark.js:269:14)
```

My test is just this simple thing::

```
'use strict';

var update = require('../lib/index');
var original = require('../lib/original');
var helper = require('../lib/helper');

var subject = helper.getNums(50);

module.exports = {
    name: 'Encode 50',
    tests: {
        'original': function () {
            original.encode(subject);
        },
        'current': function () {
            update.encode(subject);
        }
    }
};
```

it complains about vars that definitely exist, I even tried some asserts under the require()'s but for some reason things break, oddly.

This is in Node 0.11.13 on Windows using grunt-benchmark 0.3.0. I have a bunch of files like these but I glob a few at a time. Every test has this, always the first case does these errors.

**Comment by ai** [comment]
I had same issue. @shama do you have any ideas?

**Comment by ai** [comment]
You can fix it by make task deferered

**Comment by shama** [comment]
Hmm not sure, no ideas.

**Comment by ai** [comment]
Problem is that Benchmark.js stringify functions and then `eval` it. It makes many check to decide is it safe to stringify function (but this checks are not ideals). If set `defer: true` it will disable stringify.
